config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace 'admin' do
    resources :collections do
      collection do
        post :update_positions
        post :update_items_positions
      end
    end

    delete '/collection_items/:id', :to => "collection_items#destroy", :as => :collection_item
  end
end

app/models/spree/collection.rb
module Spree
  class Collection < ActiveRecord::Base
    has_many :collection_items, -> { order("position ASC") }, dependent: :destroy

    validates :name, presence: true

    accepts_nested_attributes_for :collection_items, reject_if: lambda { |ci| ci[:collectionable_type].blank? || ci[:collectionable_id].blank? }, allow_destroy: true
  end
end

app/models/spree/collection_item.rb
module Spree
  class CollectionItem < ActiveRecord::Base
    belongs_to :collection
    acts_as_list scope: :collection
    belongs_to :collectionable, :polymorphic => true
  end
end

app/controllers/spree/admin/collection_items_controller.rb
module Spree
  module Admin
    class CollectionItemsController < Spree::Admin::BaseController
      def destroy
        option_value = Spree::CollectionItem.find(params[:id])
        option_value.destroy
        render :text => nil
      end
    end
  end
end

app/controllers/spree/admin/collections_controller.rb
module Spree
  module Admin
    class CollectionsController < ResourceController

      before_filter :setup_new_collection_item, :only => [:edit]

      def update_items_positions
        params[:positions].each do |id, index|
          CollectionItem.where(:id => id).update_all(:position => index)
        end

        respond_to do |format|
          format.html { redirect_to admin_collections_url(params[:id]) }
          format.js  { render :text => 'Ok' }
        end
      end

      protected

        def location_after_save
          edit_admin_collection_url(@collection)
        end

      private

        def setup_new_collection_item
          @collection.collection_items.build if @collection.collection_items.empty?
        end

    end
  end
end

app/views/spree/admin/collections/_collection_item_fields.html.erb
<tr class="collection_item fields" id="spree_<%= dom_id(f.object) %>"  data-hook="collection_item" class="<%= cycle('odd', 'even')%>">
  <td class="move-handle">
    <% if f.object.persisted? && can?(:edit, f.object) %>
      <span class="icon icon-move handle"></span>
      <%= f.hidden_field :id %>
    <% end %>
  </td>
  <td class="collectionable_type"><%= f.select :collectionable_type, options_for_select([['Product', 'Spree::Product'],['Taxon', 'Spree::Taxon']], f.object.collectionable_type ) %></td>
  <td class="collectionable_id"><%= f.text_field :collectionable_id %></td>
  <td class="partial_override"><%= f.text_field :partial_override %></td>
  <td class="description"><%= f.text_area :description, :cols => 55, :rows => 1 %></td>
  <td class="actions actions-1">
    <% if f.object.persisted? && can?(:destroy, f.object) %>
      <%= link_to_delete f.object, no_text: true %>
    <% end %>
  </td>
</tr>

app/views/spree/admin/collections/_form.html.erb
<div data-hook="admin_collection_form_fields">
  <div class="row">
    <div class="col-md-12" data-hook="admin_product_form_left">
      <div data-hook="admin_product_form_name">
        <%= f.field_container :name, class: ['form-group'] do %>
          <%= f.label :name, Spree.t(:name) %> <span class="required">*</span><br />
          <%= f.text_field :name, :class => "form-control title" %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_description">
        <%= f.field_container :description do %>
          <%= f.label :description, Spree.t(:description) %><br />
          <%= f.text_area :description, :class => "form-control title" %>
          <%= f.error_message_on :description %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_html_class">
        <%= f.field_container :html_class do %>
          <%= f.label :html_class, Spree.t(:html_class) %><br />
          <%= f.text_field :html_class, :class => "form-control title" %>
          <%= f.error_message_on :html_class %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/collections/edit.html.erb
<% content_for :page_actions do %>
  <%= button_link_to(Spree.t(:add_collection_item), "javascript:;", { :icon => 'add', :'data-target' => "tbody#collection_items", :class => 'btn-success spree_add_fields' }) %>
  <%= button_link_to Spree.t(:back_to_collections_list), spree.admin_collections_path, :icon => 'icon-arrow-left' %>
<% end %>

<% content_for :page_title do %>
  / <%= Spree.t(:editing_collection) %> <span class="green">"<%= @collection.name %>"</span>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @collection } %>

<%= form_for [:admin, @collection] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:collection_items) %></legend>

    <%= render :partial => 'form', :locals => { :f => f } %>

    <table class="index sortable" data-hook data-sortable-link="<%= update_items_positions_admin_collections_url %>">
      <thead data-hook="option_header">
        <tr>
          <th colspan="2" width="15%"><%= Spree.t(:collectionable_type) %></th>
          <th width="10%"><%= Spree.t(:collectionable_id) %></th>
          <th width="15%"><%= Spree.t(:partial_override) %></th>
          <th width="45%"><%= Spree.t(:description) %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="collection_items">
        <% if @collection.collection_items.empty? %>
          <tr id="none" data-hook="collection_none" class="<%= cycle('odd', 'even')%>">
            <td colspan="5"><%= Spree.t(:none) %></td>
            <td class="actions"></td>
          </tr>
        <% else %>
          <%= f.fields_for :collection_items do |collection_item_form| %>
            <%= render :partial => 'collection_item_fields', :locals => { :f => collection_item_form } %>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

<p>Search Product ID</p>
<p><%= hidden_field_tag "['donotsave'][product_ids_string]", '' , :class => "product_picker_single fullwidth" %></p>
<p>Search Taxon ID</p>
<p><%= hidden_field_tag "['donotsave'][taxon_ids_string]", '' , :class => "taxon_picker_single fullwidth" %></p>

app/views/spree/admin/collections/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:collections) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_collection), new_admin_collection_url, { :remote => true, :icon => 'icon-plus', :id => 'new_collection_link' } %>
<% end %>

<div id="new_collection"></div>

<% if @collections.any? %>
  <table class="table" id="listing_collections">
    <thead>
      <tr data-hook="admin_collections_index_header">
        <th><%= Spree.t(:name) %></th>
        <th data-hook="admin_collections_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @collections.each do |collection| %>
        <tr class="spree_collection <%= cycle('odd', 'even')%>" id="<%= spree_dom_id collection %>" data-hook="option_row">
          <td><%= collection.name %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_edit collection, no_text: true, class: 'edit' if can?(:edit, collection) %>
            <%= link_to_delete collection, no_text: true if can?(:delete, collection) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/collection')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_collection_path %>!
  </div>
<% end %>

app/views/spree/admin/collections/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @collection } %>

<%= form_for [:admin, @collection] do |f| %>
  <fieldset>
    <legend align="center"><%= Spree.t(:new_collection) %></legend>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/collections/new.js.erb
$("#new_collection").html('<%= escape_javascript(render :template => "spree/admin/collections/new", :formats => [:html], :handlers => [:erb]) %>');
$("#new_collection_link").parent().hide();